config/routes.rb
Rails.application.routes.draw do
  resources :property_transactions
  resources :properties
  resources :quotations
  resources :insurances
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotations#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/insurance.rb
class Insurance < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
	has_many :property_transactions

	enum bound_by_water: { no: 0, yes: 1 }, _prefix: :bound_by_water
	enum on_municipal_water_sewer: { no: 0, yes: 1 }, _prefix: :on_municipal_water_sewer
	enum title_insurance_issued: { no: 0, yes: 1 }, _prefix: :title_insurance_issued
	enum title_insurance_denied: { no: 0, yes: 1 }, _prefix: :title_insurance_denied

end

app/models/property_transaction.rb
class PropertyTransaction < ApplicationRecord
  belongs_to :property_type
  belongs_to :property
  belongs_to :insurance
  belongs_to :quotation
  
  enum language: { english: 0, french: 1 }
  enum is_owner: { no: 0, yes: 1 }, _prefix: :is_owner

  accepts_nested_attributes_for :property
  accepts_nested_attributes_for :insurance

end

app/models/property_type.rb
class PropertyType < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
	has_one :property_transaction
	MINIMUM_VALUE_THRESHOLD=500000


	def full_name
		self.first_name.to_s + ' ' + self.last_name.to_s
	end

	def insurance_value

		value = self.municipal_evaluation.to_f

		if value < MINIMUM_VALUE_THRESHOLD
			value = MINIMUM_VALUE_THRESHOLD
		end

		form1 = (((value - 500000)/1000)*1.17)+320
		tax = form1 * 0.09
		emission_fee = 20.0
		"$" + (form1+tax+emission_fee).to_s
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/property_transactions_controller.rb
class PropertyTransactionsController < ApplicationController
  before_action :set_property_transaction, only: %i[ show edit update destroy ]

  # GET /property_transactions or /property_transactions.json
  def index
    @property_transactions = PropertyTransaction.all
  end

  # GET /property_transactions/1 or /property_transactions/1.json
  def show
  end

  # GET /property_transactions/new
  def new
    @property_transaction = PropertyTransaction.new
  end

  # GET /property_transactions/1/edit
  def edit
  end

  # POST /property_transactions or /property_transactions.json
  def create
    @property_transaction = PropertyTransaction.new(property_transaction_params)

    respond_to do |format|
      if @property_transaction.save!
        format.html { redirect_to new_quotation_url, notice: "Property transaction was successfully created." }
        format.json { render :show, status: :created, location: @property_transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_transactions/1 or /property_transactions/1.json
  def update
    respond_to do |format|
      if @property_transaction.update(property_transaction_params)
        format.html { redirect_to new_quotation_url, notice: "Property transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @property_transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_transactions/1 or /property_transactions/1.json
  def destroy
    @property_transaction.destroy

    respond_to do |format|
      format.html { redirect_to property_transactions_url, notice: "Property transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_transaction
      @property_transaction = PropertyTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_transaction_params
      params.require(:property_transaction).permit(
        :language, 
        :first_homeowner_name, 
        :second_homeowner_name, 
        :third_homeowner_name, 
        :is_owner,
        :purshase_date, 
        :property_value, 
        :property_type_id, 
        :quotation_id,
        :request_a_callback_phone,
        :request_a_callback_best_moment,
        property_attributes: [
          :id, :lot_number, :address, 
          :city, :postal_code, :on_municipal_water_sewer, :title_insurance_issued, :title_insurance_denied,
          :bound_by_water, :_destroy
        ],
        insurance_attributes: [
          :id, :notes, :referral_agent_name, :referral_agent_email, :_destroy
        ]
      )
    end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: %i[ show edit update destroy ]

  # GET /quotations or /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1 or /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    create_types
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
    @property_transaction = @quotation.property_transaction

    if @property_transaction.blank?
      @property_transaction = PropertyTransaction.new
      @property_transaction.build_property
      @property_transaction.build_insurance
      @property_transaction.first_homeowner_name = @quotation.full_name
      @property_transaction.property.address = @quotation.address
      @property_transaction.property.city = @quotation.city
      @property_transaction.property.postal_code = @quotation.postal_code
    end
  end

  # POST /quotations or /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to edit_quotation_url(@quotation), notice: "Quotation was successfully created." }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1 or /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to edit_quotation_url(@quotation), notice: "Quotation was successfully updated." }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1 or /quotations/1.json
  def destroy
    @quotation.destroy

    respond_to do |format|
      format.html { redirect_to quotations_url, notice: "Quotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quotation_params
      params.require(:quotation).permit(
        :first_name, :last_name, :email, :phone, :municipal_evaluation, :address, :postal_code, :city, 
        :referral_agent_email, :province
      )
    end

    def create_types
      if PropertyType.count == 0
        PropertyType.upsert_all(
          [
            'Single-family Dwelling', 'Condominium', 
            'Undivided co-ownership', 'Duplex', 
            'Triplex', 'Quadruplex', '5 Logis', 
            '6 Logis', 'Vacant Property'
          ].map do |name|
              {name: name}
          end
        )
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/property_transactions_helper.rb
module PropertyTransactionsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpworkAccessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/property_transactions/_form.html.erb
<h1 class="font-medium leading-tight text-4xl mt-0 mb-2 text-blue-600">Insurance Premium</h1>
<h2 class="font-small leading-tight text-4xl mt-0 mb-2 text-gray-600"><%= @quotation.insurance_value%></h2>


<div data-controller="popup-handler"> 
    <%= render partial: 'property_transactions/popup_manager' %>
  <%= form_with(model: property_transaction, html: {data: {popup_handler_target: 'mainForm'}}) do |form| %>
    <h1 class="font-medium leading-tight text-4xl mt-0 mb-2 text-blue-600"> Transaction Information </h1>

    <% if property_transaction.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(property_transaction.errors.count, "error") %> prohibited this property_transaction from being saved:</h2>

        <ul>
          <% property_transaction.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :quotation_id, value: quotation.id %>
    <%= form.hidden_field :request_a_callback_phone, data: { popup_handler_target: 'requestPhoneFieldInForm'} %>
    <%= form.hidden_field :request_a_callback_best_moment, data: { popup_handler_target: 'bestMomentFieldInForm'}  %>

    <div>
      <%= form.label :language, style: "display: block" %>
      <%= form.select(:language , PropertyTransaction.languages.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_transaction.language}, {class: "ui dropdown search"} ) %>
    </div>

    <p>Homeowner(s): Name(s):*</p>
    <div class="flex">
      <div>
        <%= form.text_field :first_homeowner_name, required: true %>
      </div>

      <div>
        <%= form.text_field :second_homeowner_name, placeholder: '2nd Homeowner Name', required: true %>
      </div>

      <div>
        <%= form.text_field :third_homeowner_name, placeholder: '3rd Homeowner Name', required: true %>
      </div>
    </div>

    <div>
      <%= form.label 'Property type*', style: "display: block" %>
      <%= form.select(:property_type_id , PropertyType.all.collect { |property| [ property.name, property.id ] }, {selected: property_transaction.property_type_id}, {class: "ui dropdown search"} ) %>
    </div>

    <div>
      <%= form.label 'Are you presently the owner of that property ?', style: "display: block" %>
      <%= form.select(:is_owner , PropertyTransaction.is_owners.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_transaction.is_owner}, {class: "ui dropdown search"} ) %>
    </div>

    <div>
      <%= form.label 'Purchase date*', style: "display: block" %>
      <%= form.date_field :purshase_date, required: true %>
      <p>You must already own your property.</p>
    </div>
    <br>
    <div>
      <p>Property value (municipal assessment): <%= quotation.municipal_evaluation %>$</p>
      <%= form.hidden_field :property_value, value: quotation.municipal_evaluation %>
    </div>

    <%= form.fields_for  :property do |property_form| %>
      <h1 class="font-medium leading-tight text-4xl mt-0 mb-2 text-blue-600"> Property Legal Description </h1>
      <p><b>Indicate (Mandatory fields):*</b></p>
      <div>
        <%= property_form.label 'Lot number(s)*', style: "display: block" %>
        <%= property_form.text_field :lot_number, required: true %>

        <p class="mt-1 mb-1">(You can find this lot number on your tax account. This is not the ID number but the lot number, cadaster number or legal description).</p>
      </div>

      <div>
        <%= property_form.label 'Property Address:*', style: "display: block" %>
        <%= property_form.text_area :address, required: true %>
      </div>

      <div>
        <%= property_form.label 'City*', style: "display: block" %>
        <%= property_form.text_field :city, required: true %>
      </div>

      <div>
        <%= property_form.label 'Postal Code*', style: "display: block" %>
        <%= property_form.text_field :postal_code, required: true %>
      </div>

      <h1 class="font-medium leading-tight text-4xl mt-0 mb-2 text-blue-600">Information regarding the property</h1>

      <div>
        <label style="display: block">Is the Insured Property bound by water (lac, stream, river, etc.)?* </label>
        <%= property_form.select(:bound_by_water , Property.bound_by_waters.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_form.object.bound_by_water}, {class: "ui dropdown search"} ) %>
      </div>

      <div>
        <%= property_form.label 'Is the Insured Property on Municipal Water and Municipal Sewer)?*', style: "display: block" %>
        <%= property_form.select(:on_municipal_water_sewer , Property.on_municipal_water_sewers.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_form.object.bound_by_water}, {class: "ui dropdown search"} ) %>
      </div>

      <div>
        <%= property_form.label 'Has a title insurance already been issued for the insured property according to the client ?*', style: "display: block" %>
        <%= property_form.select(:title_insurance_issued , Property.title_insurance_issueds.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_form.object.bound_by_water}, {class: "ui dropdown search"} ) %>
      </div>

      <div>
        <%= property_form.label "Has a title insurance been denied for the insured property, to the best of the client's knowledge?*", style: "display: block" %>
        <%= property_form.select(:title_insurance_denied , Property.title_insurance_denieds.keys.collect { |option| [ option.capitalize, option ] }, {selected: property_form.object.bound_by_water}, {class: "ui dropdown search"} ) %>
      </div>
    <% end %>

    <hr class="mt-5 mb-5">

    <%= form.fields_for :insurance do |insurance_form| %>
      <div>
        <%= insurance_form.label :notes, style: "display: block" %>
        <%= insurance_form.text_area :notes %>
      </div>

      <div>
        <%= insurance_form.label :referral_agent_name, style: "display: block" %>
        <%= insurance_form.text_field :referral_agent_name %>
      </div>

      <div>
        <%= insurance_form.label :referral_agent_email, style: "display: block" %>
        <%= insurance_form.text_field :referral_agent_email %>
      </div>
    <% end %>

    <div>
      <%= form.submit 'Request A Callback', class: 'px-6
      py-2.5
      mt-2
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      mr-1' %>
    </div>
  <% end %>
  <br>
  <br>
</div>

app/views/property_transactions/_popup_manager.html.erb
<!-- Modal -->
<div data-popup-handler-target="popup" class="hidden modal fade fixed top-150 left-0  w-full h-full outline-none overflow-x-hidden overflow-y-auto"
  id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog relative w-auto pointer-events-none">
    <div
      class="modal-content border-none shadow-lg relative flex flex-col w-full pointer-events-auto bg-white bg-clip-padding rounded-md outline-none text-current">
      <div
        class="modal-header flex flex-shrink-0 items-center justify-between p-4 border-b border-gray-200 rounded-t-md">
        <h5 class="text-xl font-medium leading-normal text-gray-800" id="exampleModalLabel">REQUEST A CALLBACK</h5>
        <button type="button"
          class="btn-close box-content w-4 h-4 p-1 text-black border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-black hover:opacity-75 hover:no-underline"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

     
      <div class="modal-body relative p-4">
        <input class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" data-popup-handler-target="number" placeholder="Phone Number" />

        <input class="mt-1 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" data-popup-handler-target="moment" placeholder="Best moment to call you"/>
      </div>

      <div
        class="modal-footer flex flex-shrink-0 flex-wrap items-center justify-end p-4 border-t border-gray-200 rounded-b-md">
        <button data-action="popup-handler#numberSubmit" type="button" class="px-6
      py-2.5
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      mr-1">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/property_transactions/_property_transaction.html.erb
<div id="<%= dom_id property_transaction %>">
  <p>
    <strong>Language:</strong>
    <%= property_transaction.language %>
  </p>

  <p>
    <strong>First homeowner name:</strong>
    <%= property_transaction.first_homeowner_name %>
  </p>

  <p>
    <strong>Second homeowner name:</strong>
    <%= property_transaction.second_homeowner_name %>
  </p>

  <p>
    <strong>Third homeowner name:</strong>
    <%= property_transaction.third_homeowner_name %>
  </p>

  <p>
    <strong>Is owner:</strong>
    <%= property_transaction.is_owner %>
  </p>

  <p>
    <strong>Purshase date:</strong>
    <%= property_transaction.purshase_date %>
  </p>

  <p>
    <strong>Property value:</strong>
    <%= property_transaction.property_value %>
  </p>

  <p>
    <strong>Property type:</strong>
    <%= property_transaction.property_type_id %>
  </p>

  <p>
    <strong>Quotation:</strong>
    <%= property_transaction.quotation_id %>
  </p>

</div>

app/views/property_transactions/edit.html.erb
<h1>Editing property transaction</h1>

<%= render "form", property_transaction: @property_transaction %>

<br>

<div>
  <%= link_to "Show this property transaction", @property_transaction %> |
  <%= link_to "Back to property transactions", property_transactions_path %>
</div>

app/views/property_transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Property transactions</h1>

<div id="property_transactions">
  <% @property_transactions.each do |property_transaction| %>
    <%= render property_transaction %>
    <p>
      <%= link_to "Show this property transaction", property_transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New property transaction", new_property_transaction_path %>

app/views/property_transactions/new.html.erb
<h1>New property transaction</h1>

<%= render "form", property_transaction: @property_transaction %>

<br>

<div>
  <%= link_to "Back to property transactions", property_transactions_path %>
</div>

app/views/property_transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property_transaction %>

<div>
  <%= link_to "Edit this property transaction", edit_property_transaction_path(@property_transaction) %> |
  <%= link_to "Back to property transactions", property_transactions_path %>

  <%= button_to "Destroy this property transaction", @property_transaction, method: :delete %>
</div>

app/views/quotations/_form.html.erb
<%= form_with(model: quotation) do |form| %>
  <% if quotation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h1 class="font-medium leading-tight text-4xl mt-0 mb-2 text-blue-600">Quotation Form</h1>
  <div class="flex">
    <div class="mr-2">
      <div>
        <%= form.text_field :first_name, placeholder: 'First name*', required: true %>
      </div>

      <div>
        <%= form.text_field :last_name, placeholder: 'Last name*', required: true  %>
      </div>

      <div>
        <%= form.email_field :email, placeholder: 'Email*', required: true %>
      </div>

      <div>
        <%= form.phone_field :phone, placeholder: 'Phone*', required: true %>
      </div>

      <div>
        <%= form.number_field :municipal_evaluation, placeholder: 'Municipal Evaluation of the property*', required: true %>
      </div>
    </div>
    <div>
      <div>
        <%= form.text_field :address, placeholder: 'Address*', required: true %>
      </div>

      <div>
        <%= form.text_field :postal_code, placeholder: 'Postal code*', required: true %>
      </div>

      <div>
        <%= form.text_field :city, placeholder: 'City*', required: true %>
      </div>

      <div>
        <%= form.text_field :province, placeholder: 'Province*', required: true %>
      </div>
    </div>
  </div>

  <div class="mt-2">
    <%= form.submit 'Get a Quote', class:"px-6
      py-2.5
      bg-blue-600
      text-white
      font-medium
      text-xs
      leading-tight
      uppercase
      rounded
      shadow-md
      hover:bg-blue-700 hover:shadow-lg
      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
      active:bg-blue-800 active:shadow-lg
      transition
      duration-150
      ease-in-out
      mr-1" %>
  </div>
  <p>*Mandatory fields</p>
<% end %>

app/views/quotations/_quotation.html.erb
<div id="<%= dom_id quotation %>">
</div>

app/views/quotations/edit.html.erb
<%= render "form", quotation: @quotation %>

<br>



<% if @quotation.present? %>
  <%= render partial: "/property_transactions/form", locals: { 
  	property_transaction: @property_transaction, 
  	quotation: @quotation } %>
<% end %>

app/views/quotations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotations</h1>

<div id="quotations">
  <% @quotations.each do |quotation| %>
    <%= render quotation %>
    <p>
      <%= link_to "Show this quotation", quotation %>
    </p>
  <% end %>
</div>

<%= link_to "New quotation", new_quotation_path %>

app/views/quotations/new.html.erb
<%= render "form", quotation: @quotation %>

app/views/quotations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quotation %>

<div>
  <%= link_to "Edit this quotation", edit_quotation_path(@quotation) %> |
  <%= link_to "Back to quotations", quotations_path %>

  <%= button_to "Destroy this quotation", @quotation, method: :delete %>
</div>